name: test

on:
  push:
    branches: [
      "main",
      "*.*.*"
    ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:

  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest  # `windows-latest`
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      # Cache your dependencies (i.e. all the stuff in your `pyproject.toml`).
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key:  ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('requirements.test.txt') }}-${{ hashFiles('requirements.txt') }}

      # The `if` statement ensures this only runs on a cache miss.
      - name: Install Dependencies
        if:  steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install --upgrade pip
          pip install -r requirements.test.txt

      - name: Check git is working
        run: |
          git config --global user.email "korawica@github.actions"
          git config --global user.name "Testing Git on Travis CI"
          git --version
          git config --list

      - name: Start Testing with pytest
        run: |
          pytest -v
